image: kaiwinter/docker-java8-maven


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - sudo apt-get install libgtk2.0-0:i386 libidn11:i386 libglu1-mesa:i386

cache:
  paths:
    - .gradle/wrapper

stages:
  - build
  - test
  - bundle
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

unitTests:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: bundle
  script:
    - ./gradlew :buildPlugin
  artifacts:
    paths:
      - build/distributions/ => plugin
    expire_in: 1 month
